kind: pipeline
name: Zaki

clone:
  depth: 1

steps:
- name: submodules
    image: alpine/git
    commands:
     - git submodule init
     - git submodule update
- name: Building
  image: fadlyas/kernel_dockerfile
  environment:
    bot_token:
      from_secret: BOT_API_KEY
    chat_id:
      from_secret: CHAT_ID
  commands:
  - bash build.sh
